# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import deploy_sdk_client
from deploy_sdk_client.rest import ApiException
from deploy_sdk_client.apis.provider_api import ProviderApi


class TestProviderApi(unittest.TestCase):
    """ ProviderApi unit test stubs """

    def setUp(self):
        self.api = deploy_sdk_client.apis.provider_api.ProviderApi()

    def tearDown(self):
        pass

    def test_delete_provider(self):
        """
        Test case for delete_provider

        Delete Provider by id
        """
        pass

    def test_get_all_providers(self):
        """
        Test case for get_all_providers

        Get allProviders for user
        """
        pass

    def test_get_aws_regions(self):
        """
        Test case for get_aws_regions

        Get all available AWS regions
        """
        pass

    def test_get_provider(self):
        """
        Test case for get_provider

        Get provider by Provider id
        """
        pass

    def test_get_provider_by_name(self):
        """
        Test case for get_provider_by_name

        Get Provider by provider name
        """
        pass

    def test_save_provider(self):
        """
        Test case for save_provider

        Create Provider for User
        """
        pass

    def test_save_provider_with_permissions(self):
        """
        Test case for save_provider_with_permissions

        Validate and Save AWS Provider
        """
        pass

    def test_update_provider(self):
        """
        Test case for update_provider

        Update existing Provider
        """
        pass


if __name__ == '__main__':
    unittest.main()
