# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import deploy_sdk_client
from deploy_sdk_client.rest import ApiException
from deploy_sdk_client.apis.package_api import PackageApi


class TestPackageApi(unittest.TestCase):
    """ PackageApi unit test stubs """

    def setUp(self):
        self.api = deploy_sdk_client.apis.package_api.PackageApi()

    def tearDown(self):
        pass

    def test_add_ansible_package(self):
        """
        Test case for add_ansible_package

        Create an ansible package by uploading zip folder
        """
        pass

    def test_add_package(self):
        """
        Test case for add_package

        Create a package
        """
        pass

    def test_create_new_version(self):
        """
        Test case for create_new_version

        Create a new Version
        """
        pass

    def test_delete_package(self):
        """
        Test case for delete_package

        Delete a package by id
        """
        pass

    def test_get_all_packages(self):
        """
        Test case for get_all_packages

        Get all available packages
        """
        pass

    def test_get_all_unique_package(self):
        """
        Test case for get_all_unique_package

        Get all packages with unique names
        """
        pass

    def test_get_default_package_type(self):
        """
        Test case for get_default_package_type

        Returns the only package type can be used on particular server.
        """
        pass

    def test_get_package(self):
        """
        Test case for get_package

        Get a package by id
        """
        pass

    def test_get_package_templates(self):
        """
        Test case for get_package_templates

        Package JSON Template with sample values which can be used to create/modify packages
        """
        pass

    def test_get_packages(self):
        """
        Test case for get_packages

        Get all packages by name and type
        """
        pass

    def test_get_shared_package_policy(self):
        """
        Test case for get_shared_package_policy

        Get shared package policy
        """
        pass

    def test_share_package(self):
        """
        Test case for share_package

        Change Package sharing policy
        """
        pass

    def test_update_packages(self):
        """
        Test case for update_packages

        Updates all packages form central packages repository
        """
        pass

    def test_update_packages_0(self):
        """
        Test case for update_packages_0

        Updates a package
        """
        pass


if __name__ == '__main__':
    unittest.main()
