# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import deploy_sdk_client
from deploy_sdk_client.rest import ApiException
from deploy_sdk_client.models.configuration_used_for_copydeploy_api import ConfigurationUsedForCopydeployAPI


class TestConfigurationUsedForCopydeployAPI(unittest.TestCase):
    """ ConfigurationUsedForCopydeployAPI unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConfigurationUsedForCopydeployAPI(self):
        """
        Test ConfigurationUsedForCopydeployAPI
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = deploy_sdk_client.models.configuration_used_for_copydeploy_api.ConfigurationUsedForCopydeployAPI()
        pass


if __name__ == '__main__':
    unittest.main()
