# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import deploy_sdk_client
from deploy_sdk_client.rest import ApiException
from deploy_sdk_client.apis.blueprint_api import BlueprintApi


class TestBlueprintApi(unittest.TestCase):
    """ BlueprintApi unit test stubs """

    def setUp(self):
        self.api = deploy_sdk_client.apis.blueprint_api.BlueprintApi()

    def tearDown(self):
        pass

    def test_get_all_resources(self):
        """
        Test case for get_all_resources

        Returns the list of all the available blueprints
        """
        pass

    def test_get_read_me_file(self):
        """
        Test case for get_read_me_file

        Get the readme file content of blueprint
        """
        pass

    def test_import_blueprint(self):
        """
        Test case for import_blueprint

        Import blurprint in REAN Deploy
        """
        pass

    def test_import_blueprint_file(self):
        """
        Test case for import_blueprint_file

        Returns blueprint file.
        """
        pass

    def test_prepare_import_blueprint(self):
        """
        Test case for prepare_import_blueprint

        Prepare blueprint before importing it
        """
        pass


if __name__ == '__main__':
    unittest.main()
