#!/usr/bin/env groovy

pipeline {
  agent {
    node {
      label 'master'
    }
  }
  environment {        
    ARTIFACT_NAME = 'REANCLI'
    PYTHON_CMD = '/usr/local/bin/python3'
    PIP_CMD = '/usr/local/bin/pip3'
  }
    stages {
    stage('Workspace Cleanup') {
        steps {
            deleteDir()
      }
    }
    
    stage('Checkout DeployNow repo and Build Swagger') { 
      steps {
      git branch: "DEP-7026", credentialsId: '78b43893-ffd7-4e04-9439-065fc6763913', url: 'https://github.com/reancloud/reanplatform-cli.git'
      sh '''
      wget http://central.maven.org/maven2/io/swagger/swagger-codegen-cli/2.2.3/swagger-codegen-cli-2.2.3.jar -O swagger-codegen-cli.jar
      java -jar swagger-codegen-cli.jar generate -i swagger.json -l python -o ${SWAGGER_PACKAGE_NAME} -c config.json
      cat config.json
      ls
      python --version
      which python3
      which pip3
      '''
      }
    }
    
    stage('Build') {
    steps {
        withPythonEnv('/usr/local/bin/python3') {
        sh '''#!/bin/bash -l
        set -e
        python --version
        #virtualenv dev
        #source dev/bin/activate
        cd REANPlatform/
        ARTIFACT_VERSION=$(awk -v FS="VERSION =" 'NF>1{print $2}' setup.py | cut -d"'" -f2)
        ${PYTHON_CMD} setup.py bdist_wheel
        WHEEL_FILE_NAME="$(find dist/ -type f -printf "%f\n")"
        ${PIP_CMD} install dist/${WHEEL_FILE_NAME} --upgrade
        zip -r ${ARTIFACT_NAME}-v${ARTIFACT_VERSION}-${BUILD_NUMBER}.zip *
        '''
        }
      }
    }
    stage("Publish to S3") {
    steps {
        sh ''' 
          export AWS_DEFAULT_REGION=us-east-1
          export AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID"
          export AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY"
          cd REANPlatform;
          echo "Creating Zip ..."
          aws s3 cp *.zip ${S3_PATH}
          echo "Copying Artifact to S3 Completed"
        '''
        }
      }
    }
    
    post {
        always {
            deleteDir()
        }
    }
}