#!/usr/bin/env groovy

pipeline {
  agent {
    node {
      label 'master'
    }
  }
  environment {        
    ARTIFACT_NAME = 'REANCLI'
    PYTHON_CMD = '/usr/local/bin/python3'
    PIP_CMD = '/usr/local/bin/pip3'
    SWAGGER_PACKAGE_VERSION = '1.6'
    SWAGGER_PACKAGE_NAME = 'swagger'
    GITHUB_COMMON_CREDS = credentials('78b43893-ffd7-4e04-9439-065fc6763913')
    GIT_AUTH_SDK_URL = 'https://github.com/reancloud/auth-sdk-client.git'
    GIT_DEPLOY_SDK_URL = 'https://github.com/reancloud/deploy-sdk-client.git'
    S3_PATH = 'https://s3.amazonaws.com/reancli-artifacts/swagger.json'
    DEVELOP_BRANCH = 'develop'
  }
    stages {
    stage('Workspace Cleanup') {
        steps {
            deleteDir()
      }
    }
    
    stage('Checkout DeployNow Branch repo and Build Swagger.json') { 
      steps {
      git credentialsId: '78b43893-ffd7-4e04-9439-065fc6763913', url: 'https://github.com/reancloud/DeployNow.git'
      sh '''
      #!/bin/bash
      set -e
      GIT_BRANCH_COMMIT_ID="$(git log --format="%H" -n 1)"
      GIT_BRANCH_NAME="$(git name-rev "${GIT_BRANCH_COMMIT_ID}" | cut -d' ' -f2- | cut -d'/' -f3-)"
      if [[ $GIT_BRANCH_NAME == DEP-7042 ]]
      then
          echo "Building from Develop Branch .."
          git checkout develop
          wget ${S3_PATH}
          echo {\n  \"packageName\": \"${SWAGGER_PACKAGE_NAME}\",\n  \"projectName\": \"${SWAGGER_PACKAGE_NAME}\",\n  \"packageVersion\": \"${SWAGGER_PACKAGE_VERSION}\"\n} > config.json
          #wget http://central.maven.org/maven2/io/swagger/swagger-codegen-cli/2.2.3/swagger-codegen-cli-2.2.3.jar -O swagger-codegen-cli.jar
          #java -jar swagger-codegen-cli.jar generate -i swagger.json -l python -o ${SWAGGER_PACKAGE_NAME} -c config.json
          mv ${SWAGGER_PACKAGE_NAME} ${SWAGGER_PACKAGE_NAME}-${SWAGGER_PACKAGE_VERSION}
          ls
          echo "Building from Develop Branch Completed."
      elif [[ $GIT_BRANCH_NAME == master ]]
      then
          echo "Building from Master Branch .."
          wget ${S3_PATH}
          echo {\n  \"packageName\": \"${SWAGGER_PACKAGE_NAME}\",\n  \"projectName\": \"${SWAGGER_PACKAGE_NAME}\",\n  \"packageVersion\": \"${SWAGGER_PACKAGE_VERSION}\"\n} > config.json
          #wget http://central.maven.org/maven2/io/swagger/swagger-codegen-cli/2.2.3/swagger-codegen-cli-2.2.3.jar -O swagger-codegen-cli.jar
          #java -jar swagger-codegen-cli.jar generate -i swagger.json -l python -o ${SWAGGER_PACKAGE_NAME} -c config.json
          #mv ${SWAGGER_PACKAGE_NAME} ${SWAGGER_PACKAGE_NAME}-${SWAGGER_PACKAGE_VERSION}
          ls
          echo "Building from Master Branch Completed."
      else
          echo "Not Develop/Master Branch. Skipping ...."
      fi
      #echo "${GIT_BRANCH_NAME},${GIT_BRANCH_COMMIT_ID}" > info.txt
      '''
      }
      }

    stage('Push Swagger.json in deploy-sdk-client Git repo') {
    steps {
    git credentialsId: '78b43893-ffd7-4e04-9439-065fc6763913', url: 'https://github.com/reancloud/DeployNow.git'
        sh '''
        #!/bin/bash
        export SWAGGER_JAR="$SWAGGER_PACKAGE_NAME-$SWAGGER_PACKAGE_VERSION"
        GIT_BRANCH_NAME="$(cat info.txt | cut -d ',' -f1)"
        GIT_BRANCH_COMMIT_ID="$(cat info.txt | cut -d ',' -f2)"
        if [[ $BRANCH_CHECK == DEVELOP ]];
        then
            ls
            git add $SWAGGER_JAR
            git commit -m "Adding swagger.json for ${GIT_BRANCH_COMMIT_ID} on develop branch"
            git push origin develop
        elif [[ $BRANCH_CHECK == MASTER ]];
        then
            git checkout master
            ls
            git add $SWAGGER_JAR
            git commit -m "Adding swagger.json for ${GIT_BRANCH_COMMIT_ID} on develop branch"
            git push origin develop
        else
            echo "Not Develop/Master Branch. Skipping ...."
        fi
        '''
      }
    }
    
    stage('Push Swagger.json in auth-sdk-client Git repo') {
    steps {
        git credentialsId: '78b43893-ffd7-4e04-9439-065fc6763913', url: 'https://github.com/reancloud/DeployNow.git'
        sh '''
        #!/bin/bash -l
        set -e
        export SWAGGER_JAR="$SWAGGER_PACKAGE_NAME-$SWAGGER_PACKAGE_VERSION"
        BRANCH_CHECK="$(cat info.txt | cut -d ',' -f1)"
        GIT_BRANCH_COMMIT_ID="$(cat info.txt | cut -d ',' -f2)"
        if [[ $BRANCH_CHECK == DEVELOP ]];
        then
            ls
            git add swagger.json
            git commit -m "Adding swagger.json for ${GIT_BRANCH_COMMIT_ID} on develop branch"
            git push origin develop
        elif [[ $BRANCH_CHECK == MASTER ]];
        then
            git branch: "master", credentialsId: '78b43893-ffd7-4e04-9439-065fc6763913', url: 'https://github.com/reancloud/deploy-sdk-client.git'
            ls
            git add swagger.json
            git commit -m "Adding swagger.json for ${GIT_BRANCH_COMMIT_ID} on develop branch"
            git push origin develop
        else
            echo "Not Develop/Master Branch. Skipping ...."
        fi
        '''
      }
    }
    }
    
    post {
        always {
            deleteDir()
        }
    }
}