# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class AWSPriceMap(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'resource_name': 'str',
        'price_map': 'dict(str, AWSPrice)'
    }

    attribute_map = {
        'resource_name': 'resourceName',
        'price_map': 'priceMap'
    }

    def __init__(self, resource_name=None, price_map=None):
        """
        AWSPriceMap - a model defined in Swagger
        """

        self._resource_name = None
        self._price_map = None

        if resource_name is not None:
          self.resource_name = resource_name
        if price_map is not None:
          self.price_map = price_map

    @property
    def resource_name(self):
        """
        Gets the resource_name of this AWSPriceMap.

        :return: The resource_name of this AWSPriceMap.
        :rtype: str
        """
        return self._resource_name

    @resource_name.setter
    def resource_name(self, resource_name):
        """
        Sets the resource_name of this AWSPriceMap.

        :param resource_name: The resource_name of this AWSPriceMap.
        :type: str
        """

        self._resource_name = resource_name

    @property
    def price_map(self):
        """
        Gets the price_map of this AWSPriceMap.

        :return: The price_map of this AWSPriceMap.
        :rtype: dict(str, AWSPrice)
        """
        return self._price_map

    @price_map.setter
    def price_map(self, price_map):
        """
        Sets the price_map of this AWSPriceMap.

        :param price_map: The price_map of this AWSPriceMap.
        :type: dict(str, AWSPrice)
        """

        self._price_map = price_map

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, AWSPriceMap):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
