# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ChefServerRunListItem(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'item': 'str',
        'sequence': 'int'
    }

    attribute_map = {
        'id': 'id',
        'item': 'item',
        'sequence': 'sequence'
    }

    def __init__(self, id=None, item=None, sequence=None):
        """
        ChefServerRunListItem - a model defined in Swagger
        """

        self._id = None
        self._item = None
        self._sequence = None

        if id is not None:
          self.id = id
        if item is not None:
          self.item = item
        if sequence is not None:
          self.sequence = sequence

    @property
    def id(self):
        """
        Gets the id of this ChefServerRunListItem.

        :return: The id of this ChefServerRunListItem.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this ChefServerRunListItem.

        :param id: The id of this ChefServerRunListItem.
        :type: int
        """

        self._id = id

    @property
    def item(self):
        """
        Gets the item of this ChefServerRunListItem.

        :return: The item of this ChefServerRunListItem.
        :rtype: str
        """
        return self._item

    @item.setter
    def item(self, item):
        """
        Sets the item of this ChefServerRunListItem.

        :param item: The item of this ChefServerRunListItem.
        :type: str
        """

        self._item = item

    @property
    def sequence(self):
        """
        Gets the sequence of this ChefServerRunListItem.

        :return: The sequence of this ChefServerRunListItem.
        :rtype: int
        """
        return self._sequence

    @sequence.setter
    def sequence(self, sequence):
        """
        Sets the sequence of this ChefServerRunListItem.

        :param sequence: The sequence of this ChefServerRunListItem.
        :type: int
        """

        self._sequence = sequence

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ChefServerRunListItem):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
