# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class DeploymentDetail(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'deployment_name': 'str',
        'deployment_id': 'int'
    }

    attribute_map = {
        'deployment_name': 'deploymentName',
        'deployment_id': 'deploymentId'
    }

    def __init__(self, deployment_name=None, deployment_id=None):
        """
        DeploymentDetail - a model defined in Swagger
        """

        self._deployment_name = None
        self._deployment_id = None

        if deployment_name is not None:
          self.deployment_name = deployment_name
        if deployment_id is not None:
          self.deployment_id = deployment_id

    @property
    def deployment_name(self):
        """
        Gets the deployment_name of this DeploymentDetail.

        :return: The deployment_name of this DeploymentDetail.
        :rtype: str
        """
        return self._deployment_name

    @deployment_name.setter
    def deployment_name(self, deployment_name):
        """
        Sets the deployment_name of this DeploymentDetail.

        :param deployment_name: The deployment_name of this DeploymentDetail.
        :type: str
        """

        self._deployment_name = deployment_name

    @property
    def deployment_id(self):
        """
        Gets the deployment_id of this DeploymentDetail.

        :return: The deployment_id of this DeploymentDetail.
        :rtype: int
        """
        return self._deployment_id

    @deployment_id.setter
    def deployment_id(self, deployment_id):
        """
        Sets the deployment_id of this DeploymentDetail.

        :param deployment_id: The deployment_id of this DeploymentDetail.
        :type: int
        """

        self._deployment_id = deployment_id

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, DeploymentDetail):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
