# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class DNBlueprint(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'short_name': 'str',
        'image': 'str'
    }

    attribute_map = {
        'name': 'name',
        'short_name': 'shortName',
        'image': 'image'
    }

    def __init__(self, name=None, short_name=None, image=None):
        """
        DNBlueprint - a model defined in Swagger
        """

        self._name = None
        self._short_name = None
        self._image = None

        if name is not None:
          self.name = name
        if short_name is not None:
          self.short_name = short_name
        if image is not None:
          self.image = image

    @property
    def name(self):
        """
        Gets the name of this DNBlueprint.
        Name of the Sub Category Catalog

        :return: The name of this DNBlueprint.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this DNBlueprint.
        Name of the Sub Category Catalog

        :param name: The name of this DNBlueprint.
        :type: str
        """

        self._name = name

    @property
    def short_name(self):
        """
        Gets the short_name of this DNBlueprint.
        Short Name for resource

        :return: The short_name of this DNBlueprint.
        :rtype: str
        """
        return self._short_name

    @short_name.setter
    def short_name(self, short_name):
        """
        Sets the short_name of this DNBlueprint.
        Short Name for resource

        :param short_name: The short_name of this DNBlueprint.
        :type: str
        """

        self._short_name = short_name

    @property
    def image(self):
        """
        Gets the image of this DNBlueprint.
        image Url of the resource

        :return: The image of this DNBlueprint.
        :rtype: str
        """
        return self._image

    @image.setter
    def image(self, image):
        """
        Sets the image of this DNBlueprint.
        image Url of the resource

        :param image: The image of this DNBlueprint.
        :type: str
        """

        self._image = image

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, DNBlueprint):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
