# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class EnvPackageAttr(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'name': 'str',
        'type': 'str',
        'required': 'bool',
        'value': 'str',
        'secure': 'bool',
        'possible_values': 'list[str]',
        'default_value': 'str'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'type': 'type',
        'required': 'required',
        'value': 'value',
        'secure': 'secure',
        'possible_values': 'possibleValues',
        'default_value': 'defaultValue'
    }

    def __init__(self, id=None, name=None, type=None, required=None, value=None, secure=None, possible_values=None, default_value=None):
        """
        EnvPackageAttr - a model defined in Swagger
        """

        self._id = None
        self._name = None
        self._type = None
        self._required = None
        self._value = None
        self._secure = None
        self._possible_values = None
        self._default_value = None

        if id is not None:
          self.id = id
        self.name = name
        self.type = type
        if required is not None:
          self.required = required
        if value is not None:
          self.value = value
        if secure is not None:
          self.secure = secure
        if possible_values is not None:
          self.possible_values = possible_values
        if default_value is not None:
          self.default_value = default_value

    @property
    def id(self):
        """
        Gets the id of this EnvPackageAttr.

        :return: The id of this EnvPackageAttr.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this EnvPackageAttr.

        :param id: The id of this EnvPackageAttr.
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """
        Gets the name of this EnvPackageAttr.
        Name of the Attribute

        :return: The name of this EnvPackageAttr.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this EnvPackageAttr.
        Name of the Attribute

        :param name: The name of this EnvPackageAttr.
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    @property
    def type(self):
        """
        Gets the type of this EnvPackageAttr.
        Type of the Attribute

        :return: The type of this EnvPackageAttr.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this EnvPackageAttr.
        Type of the Attribute

        :param type: The type of this EnvPackageAttr.
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")

        self._type = type

    @property
    def required(self):
        """
        Gets the required of this EnvPackageAttr.
        If attribute value must be set

        :return: The required of this EnvPackageAttr.
        :rtype: bool
        """
        return self._required

    @required.setter
    def required(self, required):
        """
        Sets the required of this EnvPackageAttr.
        If attribute value must be set

        :param required: The required of this EnvPackageAttr.
        :type: bool
        """

        self._required = required

    @property
    def value(self):
        """
        Gets the value of this EnvPackageAttr.
        Value of the attribute

        :return: The value of this EnvPackageAttr.
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """
        Sets the value of this EnvPackageAttr.
        Value of the attribute

        :param value: The value of this EnvPackageAttr.
        :type: str
        """

        self._value = value

    @property
    def secure(self):
        """
        Gets the secure of this EnvPackageAttr.
        Is this a secure attribute like password

        :return: The secure of this EnvPackageAttr.
        :rtype: bool
        """
        return self._secure

    @secure.setter
    def secure(self, secure):
        """
        Sets the secure of this EnvPackageAttr.
        Is this a secure attribute like password

        :param secure: The secure of this EnvPackageAttr.
        :type: bool
        """

        self._secure = secure

    @property
    def possible_values(self):
        """
        Gets the possible_values of this EnvPackageAttr.
        Possible values for the attribute.

        :return: The possible_values of this EnvPackageAttr.
        :rtype: list[str]
        """
        return self._possible_values

    @possible_values.setter
    def possible_values(self, possible_values):
        """
        Sets the possible_values of this EnvPackageAttr.
        Possible values for the attribute.

        :param possible_values: The possible_values of this EnvPackageAttr.
        :type: list[str]
        """

        self._possible_values = possible_values

    @property
    def default_value(self):
        """
        Gets the default_value of this EnvPackageAttr.
        default Value which can be fetched from Package API

        :return: The default_value of this EnvPackageAttr.
        :rtype: str
        """
        return self._default_value

    @default_value.setter
    def default_value(self, default_value):
        """
        Sets the default_value of this EnvPackageAttr.
        default Value which can be fetched from Package API

        :param default_value: The default_value of this EnvPackageAttr.
        :type: str
        """

        self._default_value = default_value

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, EnvPackageAttr):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
