# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ExportedResource(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'resource_name': 'str',
        'attributes': 'dict(str, str)',
        'connection_name': 'str',
        'connection_type': 'str',
        'count': 'str',
        'custom_connection': 'str',
        'depends_on': 'str',
        'ignore_changes': 'str',
        'packages': 'list[ExportedPackage]',
        'position_x': 'int',
        'position_y': 'int',
        'prevent_destroy': 'bool',
        'resource_type': 'str'
    }

    attribute_map = {
        'name': 'name',
        'resource_name': 'resourceName',
        'attributes': 'attributes',
        'connection_name': 'connectionName',
        'connection_type': 'connectionType',
        'count': 'count',
        'custom_connection': 'customConnection',
        'depends_on': 'dependsOn',
        'ignore_changes': 'ignoreChanges',
        'packages': 'packages',
        'position_x': 'positionX',
        'position_y': 'positionY',
        'prevent_destroy': 'preventDestroy',
        'resource_type': 'resourceType'
    }

    def __init__(self, name=None, resource_name=None, attributes=None, connection_name=None, connection_type=None, count=None, custom_connection=None, depends_on=None, ignore_changes=None, packages=None, position_x=None, position_y=None, prevent_destroy=None, resource_type=None):
        """
        ExportedResource - a model defined in Swagger
        """

        self._name = None
        self._resource_name = None
        self._attributes = None
        self._connection_name = None
        self._connection_type = None
        self._count = None
        self._custom_connection = None
        self._depends_on = None
        self._ignore_changes = None
        self._packages = None
        self._position_x = None
        self._position_y = None
        self._prevent_destroy = None
        self._resource_type = None

        if name is not None:
          self.name = name
        if resource_name is not None:
          self.resource_name = resource_name
        if attributes is not None:
          self.attributes = attributes
        if connection_name is not None:
          self.connection_name = connection_name
        if connection_type is not None:
          self.connection_type = connection_type
        if count is not None:
          self.count = count
        if custom_connection is not None:
          self.custom_connection = custom_connection
        if depends_on is not None:
          self.depends_on = depends_on
        if ignore_changes is not None:
          self.ignore_changes = ignore_changes
        if packages is not None:
          self.packages = packages
        if position_x is not None:
          self.position_x = position_x
        if position_y is not None:
          self.position_y = position_y
        if prevent_destroy is not None:
          self.prevent_destroy = prevent_destroy
        if resource_type is not None:
          self.resource_type = resource_type

    @property
    def name(self):
        """
        Gets the name of this ExportedResource.

        :return: The name of this ExportedResource.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this ExportedResource.

        :param name: The name of this ExportedResource.
        :type: str
        """

        self._name = name

    @property
    def resource_name(self):
        """
        Gets the resource_name of this ExportedResource.

        :return: The resource_name of this ExportedResource.
        :rtype: str
        """
        return self._resource_name

    @resource_name.setter
    def resource_name(self, resource_name):
        """
        Sets the resource_name of this ExportedResource.

        :param resource_name: The resource_name of this ExportedResource.
        :type: str
        """

        self._resource_name = resource_name

    @property
    def attributes(self):
        """
        Gets the attributes of this ExportedResource.

        :return: The attributes of this ExportedResource.
        :rtype: dict(str, str)
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes):
        """
        Sets the attributes of this ExportedResource.

        :param attributes: The attributes of this ExportedResource.
        :type: dict(str, str)
        """

        self._attributes = attributes

    @property
    def connection_name(self):
        """
        Gets the connection_name of this ExportedResource.

        :return: The connection_name of this ExportedResource.
        :rtype: str
        """
        return self._connection_name

    @connection_name.setter
    def connection_name(self, connection_name):
        """
        Sets the connection_name of this ExportedResource.

        :param connection_name: The connection_name of this ExportedResource.
        :type: str
        """

        self._connection_name = connection_name

    @property
    def connection_type(self):
        """
        Gets the connection_type of this ExportedResource.

        :return: The connection_type of this ExportedResource.
        :rtype: str
        """
        return self._connection_type

    @connection_type.setter
    def connection_type(self, connection_type):
        """
        Sets the connection_type of this ExportedResource.

        :param connection_type: The connection_type of this ExportedResource.
        :type: str
        """

        self._connection_type = connection_type

    @property
    def count(self):
        """
        Gets the count of this ExportedResource.

        :return: The count of this ExportedResource.
        :rtype: str
        """
        return self._count

    @count.setter
    def count(self, count):
        """
        Sets the count of this ExportedResource.

        :param count: The count of this ExportedResource.
        :type: str
        """

        self._count = count

    @property
    def custom_connection(self):
        """
        Gets the custom_connection of this ExportedResource.

        :return: The custom_connection of this ExportedResource.
        :rtype: str
        """
        return self._custom_connection

    @custom_connection.setter
    def custom_connection(self, custom_connection):
        """
        Sets the custom_connection of this ExportedResource.

        :param custom_connection: The custom_connection of this ExportedResource.
        :type: str
        """

        self._custom_connection = custom_connection

    @property
    def depends_on(self):
        """
        Gets the depends_on of this ExportedResource.

        :return: The depends_on of this ExportedResource.
        :rtype: str
        """
        return self._depends_on

    @depends_on.setter
    def depends_on(self, depends_on):
        """
        Sets the depends_on of this ExportedResource.

        :param depends_on: The depends_on of this ExportedResource.
        :type: str
        """

        self._depends_on = depends_on

    @property
    def ignore_changes(self):
        """
        Gets the ignore_changes of this ExportedResource.

        :return: The ignore_changes of this ExportedResource.
        :rtype: str
        """
        return self._ignore_changes

    @ignore_changes.setter
    def ignore_changes(self, ignore_changes):
        """
        Sets the ignore_changes of this ExportedResource.

        :param ignore_changes: The ignore_changes of this ExportedResource.
        :type: str
        """

        self._ignore_changes = ignore_changes

    @property
    def packages(self):
        """
        Gets the packages of this ExportedResource.

        :return: The packages of this ExportedResource.
        :rtype: list[ExportedPackage]
        """
        return self._packages

    @packages.setter
    def packages(self, packages):
        """
        Sets the packages of this ExportedResource.

        :param packages: The packages of this ExportedResource.
        :type: list[ExportedPackage]
        """

        self._packages = packages

    @property
    def position_x(self):
        """
        Gets the position_x of this ExportedResource.

        :return: The position_x of this ExportedResource.
        :rtype: int
        """
        return self._position_x

    @position_x.setter
    def position_x(self, position_x):
        """
        Sets the position_x of this ExportedResource.

        :param position_x: The position_x of this ExportedResource.
        :type: int
        """

        self._position_x = position_x

    @property
    def position_y(self):
        """
        Gets the position_y of this ExportedResource.

        :return: The position_y of this ExportedResource.
        :rtype: int
        """
        return self._position_y

    @position_y.setter
    def position_y(self, position_y):
        """
        Sets the position_y of this ExportedResource.

        :param position_y: The position_y of this ExportedResource.
        :type: int
        """

        self._position_y = position_y

    @property
    def prevent_destroy(self):
        """
        Gets the prevent_destroy of this ExportedResource.

        :return: The prevent_destroy of this ExportedResource.
        :rtype: bool
        """
        return self._prevent_destroy

    @prevent_destroy.setter
    def prevent_destroy(self, prevent_destroy):
        """
        Sets the prevent_destroy of this ExportedResource.

        :param prevent_destroy: The prevent_destroy of this ExportedResource.
        :type: bool
        """

        self._prevent_destroy = prevent_destroy

    @property
    def resource_type(self):
        """
        Gets the resource_type of this ExportedResource.

        :return: The resource_type of this ExportedResource.
        :rtype: str
        """
        return self._resource_type

    @resource_type.setter
    def resource_type(self, resource_type):
        """
        Sets the resource_type of this ExportedResource.

        :param resource_type: The resource_type of this ExportedResource.
        :type: str
        """
        allowed_values = ["RESOURCE", "DATA_SOURCE"]
        if resource_type not in allowed_values:
            raise ValueError(
                "Invalid value for `resource_type` ({0}), must be one of {1}"
                .format(resource_type, allowed_values)
            )

        self._resource_type = resource_type

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ExportedResource):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
