# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ExportedPackage(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'type': 'str',
        'version': 'str',
        'attributes': 'dict(str, str)'
    }

    attribute_map = {
        'name': 'name',
        'type': 'type',
        'version': 'version',
        'attributes': 'attributes'
    }

    def __init__(self, name=None, type=None, version=None, attributes=None):
        """
        ExportedPackage - a model defined in Swagger
        """

        self._name = None
        self._type = None
        self._version = None
        self._attributes = None

        if name is not None:
          self.name = name
        if type is not None:
          self.type = type
        if version is not None:
          self.version = version
        if attributes is not None:
          self.attributes = attributes

    @property
    def name(self):
        """
        Gets the name of this ExportedPackage.

        :return: The name of this ExportedPackage.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this ExportedPackage.

        :param name: The name of this ExportedPackage.
        :type: str
        """

        self._name = name

    @property
    def type(self):
        """
        Gets the type of this ExportedPackage.

        :return: The type of this ExportedPackage.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this ExportedPackage.

        :param type: The type of this ExportedPackage.
        :type: str
        """

        self._type = type

    @property
    def version(self):
        """
        Gets the version of this ExportedPackage.

        :return: The version of this ExportedPackage.
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """
        Sets the version of this ExportedPackage.

        :param version: The version of this ExportedPackage.
        :type: str
        """

        self._version = version

    @property
    def attributes(self):
        """
        Gets the attributes of this ExportedPackage.

        :return: The attributes of this ExportedPackage.
        :rtype: dict(str, str)
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes):
        """
        Sets the attributes of this ExportedPackage.

        :param attributes: The attributes of this ExportedPackage.
        :type: dict(str, str)
        """

        self._attributes = attributes

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ExportedPackage):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
