# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class MultipleBlueprintImport(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'description': 'str',
        'defaultconnection': 'int',
        'defaultprovider': 'int',
        'blueprints': 'list[DNBlueprint]'
    }

    attribute_map = {
        'name': 'name',
        'description': 'description',
        'defaultconnection': 'defaultconnection',
        'defaultprovider': 'defaultprovider',
        'blueprints': 'blueprints'
    }

    def __init__(self, name=None, description=None, defaultconnection=None, defaultprovider=None, blueprints=None):
        """
        MultipleBlueprintImport - a model defined in Swagger
        """

        self._name = None
        self._description = None
        self._defaultconnection = None
        self._defaultprovider = None
        self._blueprints = None

        if name is not None:
          self.name = name
        if description is not None:
          self.description = description
        if defaultconnection is not None:
          self.defaultconnection = defaultconnection
        if defaultprovider is not None:
          self.defaultprovider = defaultprovider
        if blueprints is not None:
          self.blueprints = blueprints

    @property
    def name(self):
        """
        Gets the name of this MultipleBlueprintImport.

        :return: The name of this MultipleBlueprintImport.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this MultipleBlueprintImport.

        :param name: The name of this MultipleBlueprintImport.
        :type: str
        """

        self._name = name

    @property
    def description(self):
        """
        Gets the description of this MultipleBlueprintImport.

        :return: The description of this MultipleBlueprintImport.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """
        Sets the description of this MultipleBlueprintImport.

        :param description: The description of this MultipleBlueprintImport.
        :type: str
        """

        self._description = description

    @property
    def defaultconnection(self):
        """
        Gets the defaultconnection of this MultipleBlueprintImport.

        :return: The defaultconnection of this MultipleBlueprintImport.
        :rtype: int
        """
        return self._defaultconnection

    @defaultconnection.setter
    def defaultconnection(self, defaultconnection):
        """
        Sets the defaultconnection of this MultipleBlueprintImport.

        :param defaultconnection: The defaultconnection of this MultipleBlueprintImport.
        :type: int
        """

        self._defaultconnection = defaultconnection

    @property
    def defaultprovider(self):
        """
        Gets the defaultprovider of this MultipleBlueprintImport.

        :return: The defaultprovider of this MultipleBlueprintImport.
        :rtype: int
        """
        return self._defaultprovider

    @defaultprovider.setter
    def defaultprovider(self, defaultprovider):
        """
        Sets the defaultprovider of this MultipleBlueprintImport.

        :param defaultprovider: The defaultprovider of this MultipleBlueprintImport.
        :type: int
        """

        self._defaultprovider = defaultprovider

    @property
    def blueprints(self):
        """
        Gets the blueprints of this MultipleBlueprintImport.

        :return: The blueprints of this MultipleBlueprintImport.
        :rtype: list[DNBlueprint]
        """
        return self._blueprints

    @blueprints.setter
    def blueprints(self, blueprints):
        """
        Sets the blueprints of this MultipleBlueprintImport.

        :param blueprints: The blueprints of this MultipleBlueprintImport.
        :type: list[DNBlueprint]
        """

        self._blueprints = blueprints

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, MultipleBlueprintImport):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
