# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class PackageAttribute(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'type': 'str',
        'default_json': 'list[object]',
        'default_value': 'str',
        'id': 'int',
        'possible_values': 'str',
        'possible_values_set': 'list[str]',
        'required': 'bool',
        'sample_value': 'str',
        'secure': 'bool'
    }

    attribute_map = {
        'name': 'name',
        'type': 'type',
        'default_json': 'defaultJson',
        'default_value': 'defaultValue',
        'id': 'id',
        'possible_values': 'possibleValues',
        'possible_values_set': 'possibleValuesSet',
        'required': 'required',
        'sample_value': 'sampleValue',
        'secure': 'secure'
    }

    def __init__(self, name=None, type=None, default_json=None, default_value=None, id=None, possible_values=None, possible_values_set=None, required=None, sample_value=None, secure=None):
        """
        PackageAttribute - a model defined in Swagger
        """

        self._name = None
        self._type = None
        self._default_json = None
        self._default_value = None
        self._id = None
        self._possible_values = None
        self._possible_values_set = None
        self._required = None
        self._sample_value = None
        self._secure = None

        if name is not None:
          self.name = name
        if type is not None:
          self.type = type
        if default_json is not None:
          self.default_json = default_json
        if default_value is not None:
          self.default_value = default_value
        if id is not None:
          self.id = id
        if possible_values is not None:
          self.possible_values = possible_values
        if possible_values_set is not None:
          self.possible_values_set = possible_values_set
        if required is not None:
          self.required = required
        if sample_value is not None:
          self.sample_value = sample_value
        if secure is not None:
          self.secure = secure

    @property
    def name(self):
        """
        Gets the name of this PackageAttribute.
        Name of the PackageAttribute.

        :return: The name of this PackageAttribute.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this PackageAttribute.
        Name of the PackageAttribute.

        :param name: The name of this PackageAttribute.
        :type: str
        """

        self._name = name

    @property
    def type(self):
        """
        Gets the type of this PackageAttribute.
        Name of the PackageAttribute.

        :return: The type of this PackageAttribute.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this PackageAttribute.
        Name of the PackageAttribute.

        :param type: The type of this PackageAttribute.
        :type: str
        """
        allowed_values = ["STRING", "JSON", "JSONARRAY", "STRINGARRAY", "BOOLEAN", "TEXT", "INT"]
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def default_json(self):
        """
        Gets the default_json of this PackageAttribute.
        Applicable only if type is JSON/JSONARRAY

        :return: The default_json of this PackageAttribute.
        :rtype: list[object]
        """
        return self._default_json

    @default_json.setter
    def default_json(self, default_json):
        """
        Sets the default_json of this PackageAttribute.
        Applicable only if type is JSON/JSONARRAY

        :param default_json: The default_json of this PackageAttribute.
        :type: list[object]
        """

        self._default_json = default_json

    @property
    def default_value(self):
        """
        Gets the default_value of this PackageAttribute.
        default Value for the PackageAttribute.

        :return: The default_value of this PackageAttribute.
        :rtype: str
        """
        return self._default_value

    @default_value.setter
    def default_value(self, default_value):
        """
        Sets the default_value of this PackageAttribute.
        default Value for the PackageAttribute.

        :param default_value: The default_value of this PackageAttribute.
        :type: str
        """

        self._default_value = default_value

    @property
    def id(self):
        """
        Gets the id of this PackageAttribute.

        :return: The id of this PackageAttribute.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this PackageAttribute.

        :param id: The id of this PackageAttribute.
        :type: int
        """

        self._id = id

    @property
    def possible_values(self):
        """
        Gets the possible_values of this PackageAttribute.
        possibleValues from which one of them can be set as value for EnvPackageAttribute

        :return: The possible_values of this PackageAttribute.
        :rtype: str
        """
        return self._possible_values

    @possible_values.setter
    def possible_values(self, possible_values):
        """
        Sets the possible_values of this PackageAttribute.
        possibleValues from which one of them can be set as value for EnvPackageAttribute

        :param possible_values: The possible_values of this PackageAttribute.
        :type: str
        """

        self._possible_values = possible_values

    @property
    def possible_values_set(self):
        """
        Gets the possible_values_set of this PackageAttribute.
        List of possible values

        :return: The possible_values_set of this PackageAttribute.
        :rtype: list[str]
        """
        return self._possible_values_set

    @possible_values_set.setter
    def possible_values_set(self, possible_values_set):
        """
        Sets the possible_values_set of this PackageAttribute.
        List of possible values

        :param possible_values_set: The possible_values_set of this PackageAttribute.
        :type: list[str]
        """

        self._possible_values_set = possible_values_set

    @property
    def required(self):
        """
        Gets the required of this PackageAttribute.
        true if it is required attribute

        :return: The required of this PackageAttribute.
        :rtype: bool
        """
        return self._required

    @required.setter
    def required(self, required):
        """
        Sets the required of this PackageAttribute.
        true if it is required attribute

        :param required: The required of this PackageAttribute.
        :type: bool
        """

        self._required = required

    @property
    def sample_value(self):
        """
        Gets the sample_value of this PackageAttribute.
        sample Value from which one can set value for EnvPackageAttribute

        :return: The sample_value of this PackageAttribute.
        :rtype: str
        """
        return self._sample_value

    @sample_value.setter
    def sample_value(self, sample_value):
        """
        Sets the sample_value of this PackageAttribute.
        sample Value from which one can set value for EnvPackageAttribute

        :param sample_value: The sample_value of this PackageAttribute.
        :type: str
        """

        self._sample_value = sample_value

    @property
    def secure(self):
        """
        Gets the secure of this PackageAttribute.
        true if it is secured attribute like password/secret keys

        :return: The secure of this PackageAttribute.
        :rtype: bool
        """
        return self._secure

    @secure.setter
    def secure(self, secure):
        """
        Sets the secure of this PackageAttribute.
        true if it is secured attribute like password/secret keys

        :param secure: The secure of this PackageAttribute.
        :type: bool
        """

        self._secure = secure

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, PackageAttribute):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
