# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ShareGroupPermission(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'group': 'GroupDto',
        'actions': 'list[str]'
    }

    attribute_map = {
        'group': 'group',
        'actions': 'actions'
    }

    def __init__(self, group=None, actions=None):
        """
        ShareGroupPermission - a model defined in Swagger
        """

        self._group = None
        self._actions = None

        if group is not None:
          self.group = group
        if actions is not None:
          self.actions = actions

    @property
    def group(self):
        """
        Gets the group of this ShareGroupPermission.

        :return: The group of this ShareGroupPermission.
        :rtype: GroupDto
        """
        return self._group

    @group.setter
    def group(self, group):
        """
        Sets the group of this ShareGroupPermission.

        :param group: The group of this ShareGroupPermission.
        :type: GroupDto
        """

        self._group = group

    @property
    def actions(self):
        """
        Gets the actions of this ShareGroupPermission.

        :return: The actions of this ShareGroupPermission.
        :rtype: list[str]
        """
        return self._actions

    @actions.setter
    def actions(self, actions):
        """
        Sets the actions of this ShareGroupPermission.

        :param actions: The actions of this ShareGroupPermission.
        :type: list[str]
        """
        allowed_values = ["VIEW", "EDIT", "CREATE", "DELETE", "DESTROY", "DEPLOY", "IMPORT", "EXPORT"]
        if not set(actions).issubset(set(allowed_values)):
            raise ValueError(
                "Invalid values for `actions` [{0}], must be a subset of [{1}]"
                .format(", ".join(map(str, set(actions)-set(allowed_values))),
                        ", ".join(map(str, allowed_values)))
            )

        self._actions = actions

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ShareGroupPermission):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
