# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class TFResourceAttrChangeLog(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'old_value': 'str',
        'new_value': 'str'
    }

    attribute_map = {
        'name': 'name',
        'old_value': 'oldValue',
        'new_value': 'newValue'
    }

    def __init__(self, name=None, old_value=None, new_value=None):
        """
        TFResourceAttrChangeLog - a model defined in Swagger
        """

        self._name = None
        self._old_value = None
        self._new_value = None

        if name is not None:
          self.name = name
        if old_value is not None:
          self.old_value = old_value
        if new_value is not None:
          self.new_value = new_value

    @property
    def name(self):
        """
        Gets the name of this TFResourceAttrChangeLog.

        :return: The name of this TFResourceAttrChangeLog.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this TFResourceAttrChangeLog.

        :param name: The name of this TFResourceAttrChangeLog.
        :type: str
        """

        self._name = name

    @property
    def old_value(self):
        """
        Gets the old_value of this TFResourceAttrChangeLog.

        :return: The old_value of this TFResourceAttrChangeLog.
        :rtype: str
        """
        return self._old_value

    @old_value.setter
    def old_value(self, old_value):
        """
        Sets the old_value of this TFResourceAttrChangeLog.

        :param old_value: The old_value of this TFResourceAttrChangeLog.
        :type: str
        """

        self._old_value = old_value

    @property
    def new_value(self):
        """
        Gets the new_value of this TFResourceAttrChangeLog.

        :return: The new_value of this TFResourceAttrChangeLog.
        :rtype: str
        """
        return self._new_value

    @new_value.setter
    def new_value(self, new_value):
        """
        Sets the new_value of this TFResourceAttrChangeLog.

        :param new_value: The new_value of this TFResourceAttrChangeLog.
        :type: str
        """

        self._new_value = new_value

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, TFResourceAttrChangeLog):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
